version: "3.9"

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-app
    restart: always
    ports:
      - "${PORT}:${PORT}"
    networks:
      - vue-network
networks:
  vue-network:
    driver: bridge
