export const URL_TYPE = {
  video: "/test/test.mp4",
  keyframe: "/test/merged_image.png",
  subtitles: "/test/test.vtt",
};

export const VIDEO_QUERIES: any = {
  video: [
    "images { \n source \n type \n }",
    "_id",
    "description",
    "title {\n main_title \n alt_title \n}",
    "type",
    "view",
    "total_episodes",
    "status",
    "favors",
    "episodes { \n _id \n source { \n kind \n value \n } \n epNum \n description \n thumbnail \n title \n keyframe { \n kind \n value \n } \n created_at \n view \n subtitles { \n lang \n source { \n kind \n value \n } \n label \n } \n }",
    "genres { \n _id \n name \n}",
    "rating { \n user { \n _id \n username } \n score \n }",
    "duration",
  ],
  search: [
    "images { \n source \n type \n }",
    "_id",
    "description",
    "title {\n main_title \n alt_title \n}",
    "type",
    "view",
    "total_episodes",
    "status",
    "avg_score",
    "rating { \n user { \n _id \n username } \n score \n }",
  ],
  headerSearch: [
    "_id",
    "images { \n source \n type \n }",
    "duration",
    "view",
    "total_episodes",
    "type",
    "title {\n main_title \n }",
    "avg_score",
  ],
  detail: [
    "images { \n source \n type \n }",
    "_id",
    "description",
    "title {\n main_title \n alt_title \n}",
    "type",
    "view",
    "total_episodes",
    "status",
    "season",
    "favors",
    "episodes { \n _id \n source { \n kind \n value \n } \n epNum \n title \n created_at \n view \n thumbnail \n }",
    "genres { \n _id \n name \n}",
    "tags { \n _id \n name \n}",
    "duration",
    "trailer { \n id \n site \n thumbnail \n}",
    "avg_score",
    "rating { \n user { \n _id \n username } \n score \n }",
    "relation { \n role \n related_series { \n _id \n title {\n main_title \n alt_title \n } \n images { \n source \n type \n } \n total_episodes \n status \n } \n}",
  ],
};
